const people = {
    g000: { name: 'God' },
    g001: { name: 'Jesus',       fatherId: 'j041', motherId: 'm031' },

    // Geneology of David
    d001: { name: 'Adam',        fatherId: 'g000', ageOfFatherWhenBorn:   0, ageAtDeath: 930 },
    d002: { name: 'Seth',        fatherId: 'd001', ageOfFatherWhenBorn: 130, ageAtDeath: 912 },
    d003: { name: 'Enos',        fatherId: 'd002', ageOfFatherWhenBorn: 105, ageAtDeath: 905 },
    d004: { name: 'Cainan',      fatherId: 'd003', ageOfFatherWhenBorn:  90, ageAtDeath: 910 },
    d005: { name: 'Mahalaleel',  fatherId: 'd004', ageOfFatherWhenBorn:  70, ageAtDeath: 895 },
    d006: { name: 'Jared',       fatherId: 'd005', ageOfFatherWhenBorn:  65, ageAtDeath: 962 },
    d007: { name: 'Enoch',       fatherId: 'd006', ageOfFatherWhenBorn: 162, ageAtDeath: 365 },
    d008: { name: 'Methuselah',  fatherId: 'd007', ageOfFatherWhenBorn:  65, ageAtDeath: 969 },
    d009: { name: 'Lamech',      fatherId: 'd008', ageOfFatherWhenBorn: 187, ageAtDeath: 777 },
    d010: { name: 'Noah',        fatherId: 'd009', ageOfFatherWhenBorn: 182, ageAtDeath: 950 },
    d011: { name: 'Shem',        fatherId: 'd010', ageOfFatherWhenBorn: 500, ageAtDeath: 600 },
    d012: { name: 'Arphaxad',    fatherId: 'd011', ageOfFatherWhenBorn: 100, ageAtDeath: 438 },
    d013: { name: 'Shelah',      fatherId: 'd012', ageOfFatherWhenBorn:  35, ageAtDeath: 433 },
    d014: { name: 'Eber',        fatherId: 'd013', ageOfFatherWhenBorn:  30, ageAtDeath: 464 },
    d015: { name: 'Peleg',       fatherId: 'd014', ageOfFatherWhenBorn:  34, ageAtDeath: 239 },
    d016: { name: 'Reu',         fatherId: 'd015', ageOfFatherWhenBorn:  30, ageAtDeath: 239 },
    d017: { name: 'Serug',       fatherId: 'd016', ageOfFatherWhenBorn:  32, ageAtDeath: 230 },
    d018: { name: 'Nahor',       fatherId: 'd017', ageOfFatherWhenBorn:  30, ageAtDeath: 148 },
    d019: { name: 'Terah',       fatherId: 'd018', ageOfFatherWhenBorn:  29, ageAtDeath: 205 },
    d020: { name: 'Abraham',     fatherId: 'd019', ageOfFatherWhenBorn:  70, ageAtDeath: 175, alias:'Abram' },
    d021: { name: 'Isaac',       fatherId: 'd020', ageOfFatherWhenBorn: 100, ageAtDeath: 180 },
    d022: { name: 'Jacob',       fatherId: 'd021', ageOfFatherWhenBorn:  60, ageAtDeath: 147, alias:'Israel' },
    d023: { name: 'Judah',       fatherId: 'd022', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d024: { name: 'Perez',       fatherId: 'd023', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d025: { name: 'Hezron',      fatherId: 'd024', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d026: { name: 'Ram',         fatherId: 'd025', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d027: { name: 'Amminadab',   fatherId: 'd026', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d028: { name: 'Nahshon',     fatherId: 'd027', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d029: { name: 'Sala',        fatherId: 'd028', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d030: { name: 'Boaz',        fatherId: 'd029', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d031: { name: 'Obed',        fatherId: 'd030', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d032: { name: 'Jesse',       fatherId: 'd031', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    d033: { name: 'David',       fatherId: 'd032', ageOfFatherWhenBorn:   0, ageAtDeath:  70 },

    // Joseph's Geneology
    m001: { name: 'Solomon',     fatherId: 'd033', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m002: { name: 'Rehoboam',    fatherId: 'm001', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m003: { name: 'Abijah',      fatherId: 'm002', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m004: { name: 'Asa',         fatherId: 'm003', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m005: { name: 'Jehoshaphat', fatherId: 'm004', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m006: { name: 'Joram',       fatherId: 'm005', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m007: { name: 'Ahaziah',     fatherId: 'm006', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m008: { name: 'Joash',       fatherId: 'm007', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m009: { name: 'Amaziah',     fatherId: 'm008', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m010: { name: 'Azariah',     fatherId: 'm009', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m011: { name: 'Jotham',      fatherId: 'm010', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m012: { name: 'Ahaz',        fatherId: 'm011', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m013: { name: 'Hezekiah',    fatherId: 'm012', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m014: { name: 'Manasseh',    fatherId: 'm013', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m015: { name: 'Amon',        fatherId: 'm014', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m016: { name: 'Josiah',      fatherId: 'm015', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m017: { name: 'Jehoiakim',   fatherId: 'm016', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m018: { name: 'Jeconiah',    fatherId: 'm017', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m019: { name: 'Pedaiah',     fatherId: 'm018', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m020: { name: 'Zerubbabel',  fatherId: 'm019', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m021: { name: 'Abiud',       fatherId: 'm020', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m022: { name: 'Eliakim',     fatherId: 'm021', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m023: { name: 'Azor',        fatherId: 'm022', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m024: { name: 'Zadok',       fatherId: 'm023', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m025: { name: 'Achim',       fatherId: 'm024', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m026: { name: 'Eliud',       fatherId: 'm025', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m027: { name: 'Eleazar',     fatherId: 'm026', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m028: { name: 'Matthan',     fatherId: 'm027', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m029: { name: 'Jacob',       fatherId: 'm028', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    m030: { name: 'Joseph',      fatherId: 'm029', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },

    // Luke's Geneology
    j001: { name: 'Nathan',      fatherId: 'd033', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j002: { name: 'Mattatha',    fatherId: 'j001', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j003: { name: 'Menna',       fatherId: 'j002', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j004: { name: 'Melea',       fatherId: 'j003', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j005: { name: 'Eliakim',     fatherId: 'j004', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j006: { name: 'Jonam',       fatherId: 'j005', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j007: { name: 'Joseph',      fatherId: 'j006', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j008: { name: 'Judah',       fatherId: 'j007', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j009: { name: 'Simeon',      fatherId: 'j008', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j010: { name: 'Levi',        fatherId: 'j009', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j011: { name: 'Matthat',     fatherId: 'j010', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j012: { name: 'Jorim',       fatherId: 'j011', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j013: { name: 'Eliezer',     fatherId: 'j012', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j014: { name: 'Joshua',      fatherId: 'j013', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j015: { name: 'Er',          fatherId: 'j014', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j016: { name: 'Elmadam',     fatherId: 'j015', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j017: { name: 'Cosam',       fatherId: 'j016', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j018: { name: 'Addi',        fatherId: 'j017', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j019: { name: 'Melchi',      fatherId: 'j018', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j020: { name: 'Neri',        fatherId: 'j019', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j021: { name: 'Shealtiel',   fatherId: 'j020', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j022: { name: 'Zerubbabel',  fatherId: 'j021', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j023: { name: 'Rhesa',       fatherId: 'j022', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j024: { name: 'Joanan',      fatherId: 'j023', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j025: { name: 'Joda',        fatherId: 'j024', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j026: { name: 'Josech',      fatherId: 'j025', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j027: { name: 'Semein',      fatherId: 'j026', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j028: { name: 'Mattathias',  fatherId: 'j027', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j029: { name: 'Maath',       fatherId: 'j028', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j030: { name: 'Naggai',      fatherId: 'j029', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j031: { name: 'Esli',        fatherId: 'j030', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j032: { name: 'Nahum',       fatherId: 'j031', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j033: { name: 'Amos',        fatherId: 'j032', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j034: { name: 'Mattathias',  fatherId: 'j033', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j035: { name: 'Joseph',      fatherId: 'j034', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j036: { name: 'Jannai',      fatherId: 'j035', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j037: { name: 'Melchi',      fatherId: 'j036', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j038: { name: 'Levi',        fatherId: 'j037', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j039: { name: 'Matthat',     fatherId: 'j038', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j040: { name: 'Heli',        fatherId: 'j039', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
    j041: { name: 'Joseph',      fatherId: 'j040', ageOfFatherWhenBorn:   0, ageAtDeath:   0 },
};

console.log({
    people,
});
